title =        ".NET Junkie - Weblog of a workaholic"
baseURL =      "https://blogs.cuttingedge.it/steven/"
author =       "Steven van Deursen"
theme =        "tale-hugo"
publishDir =   "../dotnetjunkie.github.io/steven/"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = 20

[Author]
  name = "Steven van Deursen"
	
[permalinks]
  posts = "posts/:year/:filename/"
  
[Params]
  css = ["/css/overrides2.css", "/css/Libre_Baskerville_400_400i_700.css"]
  
reviewers = [
	["Peter Parker", "https://www.linkedin.com/in/qujck/"],
	["Ric Slappendel", "https://www.linkedin.com/in/ricslappendel/"]
]

pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = false
pygmentsUseClassic = true
pygmentsUseClasses = true
# See https://xyproto.github.io/splash/docs/all.html for more styles
pygmentsStyle = "pygments"
