title = ".NET Junkie - Weblog of a workaholic"
baseURL = "https://blogs.cuttingedge.it/steven/"
author = "Steven van Deursen"
theme = "tale-hugo"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = 14

[Author]
	name = "Steven van Deursen"
	
[permalinks]
  posts = "posts/:year/:filename/"

pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = false
pygmentsUseClassic = true
pygmentsUseClasses = true
# See https://xyproto.github.io/splash/docs/all.html for more styles
pygmentsStyle = "pygments"
